### ISSUE TITLE
목표

### ISSUE THREAD

**Issue by csc7545** [csc7545/New_Team_Project_4#1]
1. 목표: 게임
2. 함수 정의
3. 역할 분담
4. README.md
5. WIKI

**Comment by kimpeter2018** [comment]
게임이 시작 하기 전에 사용자 정보를 받고 게임 오버 때 저장 할건지 안할건지 물어보는 방식으로 어때요?

**Comment by csc7545** [comment]
네네 좋아요.
게임은 Snake로 하고 보통 오락실 게임 끝나고 맨 뒤에 랭킹 리스트 나오니까
약간 오락실 느낌으로 하는거죠
게임 끝나면 이름 적고 점수랑 날짜 저장되게요

**Comment by kimpeter2018** [comment]
박스 안에 넣는데 m 을 누르면 crud 화면이 뜨게끔 할게요 어떤가요?
