### ISSUE TITLE
addScore 에러

### ISSUE THREAD

**Issue by kimpeter2018** [csc7545/New_Team_Project_4#14]
list 했을때 첫번째 점수가 0으로 뜨는 이유는 처음 게임을 reset 할때 s[count]의 score 값이 아닌 그냥 s->score 을 0으로 지정해주어서 그런거 같습니다. Game Structure의 몇번째 배열이 현재 다루고 있는 구조체인지 명확하게 정해주어야 할 거 같습니다

**Comment by csc7545** [comment]
그렇네요 랭킹 이름과 랭킹 점수을 동일한 순서로 위치해줘야겠어요.
이름은 넣은 순서대로 나오고 점수는 높은 순으로 출력되네요.
