### ISSUE TITLE
필요한 함수들

### ISSUE THREAD

**Issue by kimpeter2018** [csc7545/New_Team_Project_4#2]
먼저 오늘 (6일) 안에 header 파일 하나 만들어서 구조체 정의 정도만 해둘게요

**Comment by kimpeter2018** [comment]
일단 유저 정보를 어떤걸 만들어야 할 지 모르겠어서 이름이랑 나이, 점수 (점수는 게임 종료시 자동으로 입력) 정도만 두었습니다. 어떤걸 변경하면 좋을지 추가하면 좋을지 말해주세요

**Comment by csc7545** [comment]
유저 정보는 이름(닉네임??)만 하고 날짜와 점수만 하면 될거 같아요.

**Comment by csc7545** [comment]
함수 리스트
시스템 관련
1. CRUD 
2. 랭킹 출력
3. 데이터 순서
4. 파일 불러오기
5. 파일 저장

게임 관련
1. 게임 시작화면
2. 초기화
3. 게임판 테두리
4. 뱀머리 이동
5. 일시정지
6. 게임오버
7. 먹이 생성
8. 개발자용 status 표시

이정도가 되겠네요

**Comment by kimpeter2018** [comment]
그러면 역할 분담은 어떻게 하는게 좋을까요?

**Comment by csc7545** [comment]
흠 한명은 CRUD와 파일 I/O 한명은 Snake 게임을 구현하는 것이 좋을거 같아요

**Comment by csc7545** [comment]
우선 스네이크 게임 구현 완료했습니다!

**Comment by kimpeter2018** [comment]
우선은 날짜 제외하고 구현 하고 잘 작동 하면 날짜 포함 하겠습니다

**Comment by csc7545** [comment]
네네 오늘 밤에 일 끝나고 구현 해보겠습니다.

**Comment by kimpeter2018** [comment]
list 함수 관련 버그 해결 했습니다. 리스트가 내려가면서 Y값이 증가 해야하는데 그게 없어서 추가 해주었습니다
